/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.{blade.php,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fcf9f8",
        "on-background": "#1b1c1c",
        "surface-dim": "#dcd9d9",
        "on-error": "#ffffff",
        "on-surface": "#1b1c1c",
        "inverse-surface": "#303030",
        "primary": "#9e357b",
        "on-secondary-fixed": "#221b00",
        "on-tertiary": "#ffffff",
        "background": "#fcf9f8",
        "tertiary-fixed": "#c1e8ff",
        "on-secondary": "#ffffff",
        "surface-variant": "#e5e2e1",
        "on-secondary-fixed-variant": "#554500",
        "inverse-on-surface": "#f3f0ef",
        "on-tertiary-container": "#004860",
        "surface-container-highest": "#e5e2e1",
        "on-primary": "#ffffff",
        "secondary": "#705d00",
        "on-primary-fixed": "#3c002b",
        "on-secondary-container": "#715d00",
        "outline": "#86727b",
        "primary-fixed-dim": "#ffaedb",
        "surface-container-low": "#f6f3f2",
        "surface": "#fcf9f8",
        "on-error-container": "#93000a",
        "on-primary-container": "#7a135d",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#73d2ff",
        "primary-container": "#ff85d0",
        "secondary-fixed": "#ffe173",
        "surface-tint": "#9e357b",
        "surface-container": "#f0eded",
        "on-primary-fixed-variant": "#811962",
        "on-surface-variant": "#53424b",
        "tertiary": "#006687",
        "secondary-fixed-dim": "#e8c426",
        "surface-container-high": "#eae7e7",
        "outline-variant": "#d8c0cb",
        "inverse-primary": "#ffaedb",
        "tertiary-container": "#38bbef",
        "on-tertiary-fixed-variant": "#004d66",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#ffd8eb",
        "on-tertiary-fixed": "#001e2b",
        "error-container": "#ffdad6",
        "secondary-container": "#fdd73b",
        "transparent": "transparent",
        "white": "#ffffff",
        "black": "#000000",
        "gray": {
          "50": "#f9fafb",
          "100": "#f3f4f6",
          "200": "#e5e7eb",
          "300": "#d1d5db",
          "400": "#9ca3af",
          "500": "#6b7280",
          "600": "#4b5563",
          "700": "#374151",
          "800": "#1f2937",
          "900": "#111827",
        },
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px",
        "none": "0",
        "sm": "0.125rem",
        "md": "0.375rem",
      },
      spacing: {
        "0": "0",
        "1": "0.25rem",
        "2": "0.5rem",
        "3": "0.75rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "7": "1.75rem",
        "8": "2rem",
        "9": "2.25rem",
        "10": "2.5rem",
        "11": "2.75rem",
        "12": "3rem",
        "14": "3.5rem",
        "16": "4rem",
        "20": "5rem",
        "24": "6rem",
        "28": "7rem",
        "32": "8rem",
        "36": "9rem",
        "40": "10rem",
        "44": "11rem",
        "48": "12rem",
        "52": "13rem",
        "56": "14rem",
        "60": "15rem",
        "64": "16rem",
        "80": "20rem",
        "96": "24rem",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "unit": "8px",
        "gutter": "24px",
        "section-gap": "80px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "label-bold": ["Rubik", "sans-serif"],
        "price-display": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "sans": ["Be Vietnam Pro", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-1px", fontWeight: "800" }],
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "700" }],
        "price-display": ["24px", { lineHeight: "32px", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "xs": ["12px", { lineHeight: "16px" }],
        "sm": ["14px", { lineHeight: "20px" }],
        "base": ["16px", { lineHeight: "24px" }],
        "lg": ["18px", { lineHeight: "28px" }],
        "xl": ["20px", { lineHeight: "28px" }],
        "2xl": ["24px", { lineHeight: "32px" }],
      },
      boxShadow: {
        "kawaii": "4px 4px 0px 0px rgba(27,28,28,1)",
        "kawaii-lg": "8px 8px 0px 0px rgba(27,28,28,1)",
        "kawaii-xl": "12px 12px 0px 0px rgba(27,28,28,1)",
        "sm": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "base": "0 1px 3px 0 rgb(0 0 0 / 0.1)",
        "md": "0 4px 6px -1px rgb(0 0 0 / 0.1)",
        "lg": "0 10px 15px -3px rgb(0 0 0 / 0.1)",
        "none": "none",
      },
      backgroundImage: {
        "kawaii-pattern": "radial-gradient(circle, rgba(255,212,235,0.3) 1px, transparent 1px)",
        "polka-dots": "radial-gradient(circle, rgba(27,28,28,0.1) 2px, transparent 2px)",
      },
      backgroundSize: {
        "kawaii-pattern": "20px 20px",
        "polka-dots": "30px 30px",
      }
    }
  },
  plugins: [],
}
